server:
    port: 8084

jwt:
    secret: secret
    expiration: 50000
    refresh:
        expiration: 50000

spring:
    application:
        name: paymant-card-service
    datasource:
        url: jdbc:postgresql://localhost:5432/e_wallet_card
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true